### ISSUE TITLE
Add  Grizzly Bear Population Units

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/bcmaps#45]
Add [Grizzly Bear Population Units](https://catalogue.data.gov.bc.ca/dataset/grizzly-bear-population-units) to `bcmaps` + `bcmapsdata` &mdash; map layer is licensed [OGL-British Columbia](https://www2.gov.bc.ca/gov/content/data/open-data/open-government-license-bc).

**Comment by boshek** [comment]
This does strike me a little bit of different direction for bcmaps. Not opposed to this but I wonder if this is a good opportunity to discuss the scope of bcmaps. Much of the layers currently present in the package are relatively static. Because of the nature of this data, are we introducing additional maintenance as grizzly bear populations shift and change?

**Comment by ateucher** [comment]
Not needed at this time
