### ISSUE TITLE
New workflow for layers from Canada data

### ISSUE THREAD

**Issue by ateucher** [bcgov/bcmaps#61]
layers: bc_bound_hres, 2x watercourses

options:

- function(s) to download, process, and cache from Canada
- bundle in package (probably not feasible due to size)
- host as assets in a GH release similar to BEC and TSA

**Comment by boshek** [comment]
I think option `a` is the best at this point. I see these as layers needing to be pulled directly from the GoC:

- `watercourses_15M`
- `watercourses_5M`

The tw bc_bound functions are now drawn from the Catalogue. In terms of licensing, since we aren't re-distributing this data we don't actually need to specify the license correct? If we do need to specify I'm thinking the help files would be a good place?
