### ISSUE TITLE
Checking package with R_FUTURE_PLAN=multisession reveals problems

### ISSUE THREAD

**Issue by HenrikBengtsson** [bcgov/bcmaps#68]
UPDATE 2020-09-21: I've posted R CMD check output for another package.  Please discard this issue.

Hi, I run revdep checks where I force packages to use 'multisession' futures instead of 'sequential' by default.  This will help assert that the package work in parallel processing.  When I did this for your package, the following error popped up:

```
$ export R_FUTURE_PLAN=multisession
$ R CMD check https://cran.r-project.org/src/contrib/bcmaps_0.18.1.tar.gz
...
```

**Comment by ateucher** [comment]
Thanks @HenrikBengtsson, 

Somehow, this check output isn't from `bcmaps` - it looks like it's from the [steps](https://github.com/steps-dev/steps) package (here is the `kangaroo_model_example.Rmd` vignette in that package: https://github.com/steps-dev/steps/blob/master/vignettes/kangaroo_model_example.Rmd).

However I am re-checking the package with `R_FUTURE_PLAN=multisession`  and am going to rework the internals to follow your advice and rely on the user to set their future settings rather than the package doing it for them.

**Comment by HenrikBengtsson** [comment]
Oh... sorry about that.  My bad.  I must have cut'n'pasted from the wrong terminal window or log file (I had lots of the open at the same time).  I went back and looked at the `R_FUTURE_PLAN=multisession` checks on **bcmaps** and it turns out it timed out after running for 60 minutes.  So, that could reveal another type of bug.  I leave it open but please feel free to close.

**Comment by ateucher** [comment]
Yup, mine timed out too, thanks for confirming! I'll close this but I am working on it and we'll get a new version up soon. Thanks for the heads up.

**Comment by HenrikBengtsson** [comment]
Thanks.  It's on my to-do list to write a vignette on 'Best Practices For Package Developers using Futures' (https://github.com/HenrikBengtsson/future/issues/375) where this check will be included.  I just never get around to write that doc - oh well.
